# Generated by Django 5.2.8 on 2025-12-24 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_local_alter_user_document_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_worker',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
