# Generated by Django 5.2.8 on 2026-01-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_payment_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='plan_duration_days_snapshot',
        ),
    ]
