# Generated by Django 5.2.8 on 2025-12-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipment_equipmentmantenance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentMantenance',
            new_name='EquipmentMaintenance',
        ),
    ]
