# Generated by Django 5.2.8 on 2026-01-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_equipmentmantenance_equipmentmaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='local',
        ),
    ]
