# Generated by Django 5.2.8 on 2026-01-03 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_plan_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('plan_name_snapshot', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_price_snapshot', models.FloatField(default=0.0)),
                ('local_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('local_name_snapshot', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.PositiveIntegerField(choices=[(0, 'CASH'), (1, 'YAPE'), (2, 'PLIN'), (3, 'CARD')], default=0)),
                ('discount_amount', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('final_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_registered', to=settings.AUTH_USER_MODEL, verbose_name='register_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
