# Generated by Django 5.2.8 on 2025-12-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type_document',
            field=models.IntegerField(choices=[(0, 'expense'), (1, 'income')], default=0, verbose_name='expense_type'),
        ),
    ]
